In [1]:
%cd /Data/Projects/HaritoProduction

/Data/Projects/HaritoProduction


/Data/Projects/venv_manager/ai_work#311/lib/python3.11/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [2]:
from backend.app.models.ThyroidCancerClassificationModel import ThyroidCancerClassificationModel
import numpy as np
import torch

In [4]:
model = ThyroidCancerClassificationModel()

WARNING ⚠️ Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify','pose' or 'obb'.


In [33]:
# image_origin_dir = '/Data/Projects/ThyroidCancer_InfoData_Local/dataver1/test/B5/B5_53.jpg'
# image_origin_dir = '/Data/Projects/ThyroidCancer_InfoData_Local/dataver1/test/B5/B5_52.jpg'
# image_origin_dir = '/Data/Projects/ThyroidCancer_InfoData_Local/dataver1/test/B5/B5_51.jpg'
# image_origin_dir = '/Data/Projects/ThyroidCancer_InfoData_Local/dataver1/test/B5/B5_5.jpg'

image_origin_dir = '/Data/Projects/ThyroidCancer_InfoData_Local/dataver1/test/.B2/B2_9.jpg'
# image_origin_dir = '/Data/Projects/ThyroidCancer_InfoData_Local/dataver1/test/.B2/B2_7.jpg'
# image_origin_dir = '/Data/Projects/ThyroidCancer_InfoData_Local/dataver1/test/.B2/B2_1.jpg'
# image_origin_dir = '/Data/Projects/ThyroidCancer_InfoData_Local/dataver1/test/.B2/B2_2.jpg'

# image_origin_dir = '/Data/Projects/ThyroidCancer_InfoData_Local/dataver1/test/B6/B6_12.jpg'
# image_origin_dir = '/Data/Projects/ThyroidCancer_InfoData_Local/dataver1/test/B6/B6_18.jpg'
# image_origin_dir = '/Data/Projects/ThyroidCancer_InfoData_Local/dataver1/test/B6/B6_17.jpg'
# image_origin_dir = '/Data/Projects/ThyroidCancer_InfoData_Local/dataver1/test/B6/B6_1.jpg'

predict, outputs = model.forward(image_origin_dir)
print(predict, outputs[0], outputs[1], outputs[2], sep='\n')

image 1/1 /Data/Projects/ThyroidCancer_InfoData_Local/dataver1/test/.B2/B2_9.jpg: 640x640 11 clusters, 55.7ms
Speed: 3.3ms preprocess, 55.7ms inference, 0.5ms postprocess per image at shape (1, 3, 640, 640)
/Data/Projects/ThyroidCancer_InfoData_Local/dataver1/test/.B2/B2_9.jpg have 11 cell importance clusters
<class 'numpy.ndarray'> (18, 224, 224, 3) float64
<class 'torch.Tensor'> torch.Size([18, 3]) torch.float32
<class 'torch.Tensor'> torch.Size([1, 3]) torch.float32
tensor([1])
tensor([[1.3297e-28, 1.0000e+00, 3.4079e-30]], grad_fn=<SoftmaxBackward0>)
tensor([[ 6.3521e+00,  1.9821e-03, -1.4481e+00],
        [-2.3017e+02,  3.6158e+01,  2.5833e+01],
        [-3.8982e+01,  5.1955e+00,  3.5238e+00],
        [-8.4300e+01,  1.2504e+01,  8.7911e+00],
        [-1.7274e+02,  2.6765e+01,  1.9068e+01],
        [-8.4394e+01,  1.2520e+01,  8.8026e+00],
        [-7.6284e+01, -6.8383e+00, -4.4745e+00],
        [-1.2601e+02,  1.9228e+01,  1.3637e+01],
        [-9.5454e+01,  1.4302e+01,  1.0087e+01]

In [34]:
predict_list = predict.tolist()
print(predict_list)

[1]


In [7]:
images = model.get_images(image_origin_dir)

Loading /Data/Projects/HaritoProduction/backend/app/models/cell_cluster_detect_300_epoches_best.onnx for ONNX Runtime inference...

image 1/1 /Data/Projects/ThyroidCancer/Phase1/Data/origin_data/B256/B6/z5113668157517_bd34e608315184a9f85b2d3f6eff7c54.jpg: 640x640 5 clusters, 54.9ms
Speed: 7.4ms preprocess, 54.9ms inference, 5.5ms postprocess per image at shape (1, 3, 640, 640)
/Data/Projects/ThyroidCancer/Phase1/Data/origin_data/B256/B6/z5113668157517_bd34e608315184a9f85b2d3f6eff7c54.jpg have 5 cell importance clusters


In [8]:
images.shape

(18, 256, 256, 3)

In [9]:
images

array([[[[    0.79608,     0.53333,     0.70588],
         [    0.81176,     0.54902,     0.71765],
         [    0.80784,     0.52941,     0.70196],
         ...,
         [    0.99608,     0.92157,      0.9451],
         [          1,     0.92549,     0.94902],
         [          1,     0.92941,     0.95294]],

        [[    0.79216,     0.52941,     0.70196],
         [        0.8,     0.52941,     0.70196],
         [    0.76471,     0.48627,     0.65098],
         ...,
         [    0.99608,     0.92157,      0.9451],
         [          1,     0.92549,     0.94902],
         [          1,     0.92941,     0.95294]],

        [[    0.77647,     0.50588,     0.67843],
         [    0.77255,     0.50588,     0.66667],
         [    0.72941,      0.4549,         0.6],
         ...,
         [          1,     0.92549,     0.94902],
         [          1,     0.92549,     0.94902],
         [          1,     0.92549,     0.94902]],

        ...,

        [[    0.99608,     0.90588,   

In [31]:
print(model.origin_image.shape)
print(model.origin_image)

(768, 1024, 3)
[[[    0.79608     0.53333     0.70588]
  [    0.81176     0.54902     0.71765]
  [    0.80784     0.52941     0.70196]
  ...
  [    0.72549     0.46667     0.57647]
  [     0.7098     0.44706     0.57647]
  [    0.71373     0.45098     0.58039]]

 [[    0.79216     0.52941     0.70196]
  [        0.8     0.52941     0.70196]
  [    0.76471     0.48627     0.65098]
  ...
  [    0.71765     0.45882     0.56863]
  [    0.70196     0.43922     0.56078]
  [    0.70196     0.44706     0.57255]]

 [[    0.77647     0.50588     0.67843]
  [    0.77255     0.50588     0.66667]
  [    0.72941      0.4549         0.6]
  ...
  [    0.72157     0.47059     0.57647]
  [     0.7098      0.4549     0.57255]
  [    0.70588     0.45882     0.57255]]

 ...

 [[    0.98824      0.8549     0.85098]
  [    0.99216     0.87059     0.86275]
  [          1     0.88235     0.87451]
  ...
  [    0.97255     0.84706     0.90588]
  [    0.98824      0.8549     0.91765]
  [          1     0.87059   

In [32]:
images_tensor = torch.from_numpy(images).to('cpu').permute(0, 3, 1, 2)  # (B, H, W, C) -> (B, C, H, W)

import torchvision.transforms as transforms
resize_transform = transforms.Resize((224, 224))

# Áp dụng biến đổi trên từng hình ảnh trong batch
images_tensor = torch.stack([resize_transform(img) for img in images_tensor])

In [33]:
print(images_tensor.shape)
print(images_tensor.dtype)
images_tensor = images_tensor.double()  # Chuyển sang kiểu dữ liệu float64 to double (float64)
print(images_tensor.dtype)
print(images_tensor)

torch.Size([18, 3, 224, 224])
torch.float64
torch.float64
tensor([[[[0.7978, 0.8073, 0.7973,  ..., 0.9948, 0.9989, 1.0000],
          [0.7886, 0.7820, 0.7431,  ..., 0.9972, 0.9992, 1.0000],
          [0.7644, 0.7487, 0.7240,  ..., 1.0000, 1.0000, 0.9987],
          ...,
          [0.9976, 0.9972, 0.9961,  ..., 0.7421, 0.7218, 0.7056],
          [0.9937, 0.9969, 0.9967,  ..., 0.7597, 0.7355, 0.7159],
          [0.9955, 0.9972, 0.9982,  ..., 0.7808, 0.7586, 0.7371]],

         [[0.5349, 0.5392, 0.5192,  ..., 0.9203, 0.9244, 0.9288],
          [0.5229, 0.5103, 0.4669,  ..., 0.9227, 0.9247, 0.9279],
          [0.4957, 0.4799, 0.4501,  ..., 0.9255, 0.9255, 0.9242],
          ...,
          [0.9082, 0.9126, 0.9153,  ..., 0.4676, 0.4530, 0.4422],
          [0.9095, 0.9145, 0.9170,  ..., 0.4863, 0.4667, 0.4525],
          [0.9077, 0.9148, 0.9164,  ..., 0.5053, 0.4850, 0.4699]],

         [[0.7069, 0.7090, 0.6841,  ..., 0.9438, 0.9479, 0.9523],
          [0.6949, 0.6768, 0.6202,  ..., 0.9462, 0

In [35]:
# Chuyển đổi kiểu dữ liệu từ float64 (double) sang float32
images_tensor = images_tensor.float()

# Kiểm tra lại kiểu dữ liệu sau khi chuyển đổi
print(images_tensor.dtype)  # Phải là torch.float32

torch.float32


In [36]:
model.model2 = model.model2.float()
outputs_model2 = model.model2(images_tensor)

In [38]:
print(outputs_model2.shape)
print(outputs_model2)

torch.Size([18, 3])
tensor([[-4.9766e+01,  6.9319e+00,  4.7753e+00],
        [-3.2445e+01,  1.8024e+00,  1.1659e+00],
        [-1.2255e+02,  1.8667e+01,  1.3232e+01],
        [-3.7331e+01,  4.9252e+00,  3.3292e+00],
        [-1.8339e+02,  2.8629e+01,  2.0406e+01],
        [-7.5869e+01, -6.7996e+00, -4.4506e+00],
        [-6.1510e+01, -5.3561e+00, -3.5507e+00],
        [-1.8874e+01, -3.2514e-03, -1.4965e-01],
        [-5.3690e+01,  7.5607e+00,  5.2286e+00],
        [-1.7285e+02, -1.5884e+01, -1.0074e+01],
        [-4.5090e+01, -3.9153e+00, -2.6650e+00],
        [-2.0497e+02,  3.1970e+01,  2.2819e+01],
        [-3.5932e+01, -2.2110e+00, -1.5556e+00],
        [-5.5376e+01, -4.8798e+00, -3.2621e+00],
        [-1.6737e+02, -1.5371e+01, -9.7567e+00],
        [-1.9757e+02,  3.0767e+01,  2.1953e+01],
        [-5.5633e+01,  7.8743e+00,  5.4546e+00],
        [-4.3314e+01,  5.7778e+00,  3.9478e+00]], grad_fn=<AddmmBackward0>)


In [39]:
_, predicted = torch.max(outputs_model2, 1)

In [40]:
print(predicted.shape)
print(predicted)

torch.Size([18])
tensor([1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1])


In [46]:
input_model3 = outputs_model2.view(-1)
print(input_model3.shape)
print(input_model3)

torch.Size([54])
tensor([-4.9766e+01,  6.9319e+00,  4.7753e+00, -3.2445e+01,  1.8024e+00,  1.1659e+00, -1.2255e+02,  1.8667e+01,  1.3232e+01, -3.7331e+01,  4.9252e+00,  3.3292e+00, -1.8339e+02,  2.8629e+01,  2.0406e+01, -7.5869e+01, -6.7996e+00, -4.4506e+00, -6.1510e+01, -5.3561e+00, -3.5507e+00, -1.8874e+01, -3.2514e-03, -1.4965e-01,
        -5.3690e+01,  7.5607e+00,  5.2286e+00, -1.7285e+02, -1.5884e+01, -1.0074e+01, -4.5090e+01, -3.9153e+00, -2.6650e+00, -2.0497e+02,  3.1970e+01,  2.2819e+01, -3.5932e+01, -2.2110e+00, -1.5556e+00, -5.5376e+01, -4.8798e+00, -3.2621e+00, -1.6737e+02, -1.5371e+01, -9.7567e+00, -1.9757e+02,  3.0767e+01,  2.1953e+01,
        -5.5633e+01,  7.8743e+00,  5.4546e+00, -4.3314e+01,  5.7778e+00,  3.9478e+00], grad_fn=<ViewBackward0>)


In [47]:
input_model3 = input_model3.unsqueeze(0)
print(input_model3.shape)
print(input_model3)

torch.Size([1, 54])
tensor([[-4.9766e+01,  6.9319e+00,  4.7753e+00, -3.2445e+01,  1.8024e+00,  1.1659e+00, -1.2255e+02,  1.8667e+01,  1.3232e+01, -3.7331e+01,  4.9252e+00,  3.3292e+00, -1.8339e+02,  2.8629e+01,  2.0406e+01, -7.5869e+01, -6.7996e+00, -4.4506e+00, -6.1510e+01, -5.3561e+00, -3.5507e+00, -1.8874e+01, -3.2514e-03, -1.4965e-01,
         -5.3690e+01,  7.5607e+00,  5.2286e+00, -1.7285e+02, -1.5884e+01, -1.0074e+01, -4.5090e+01, -3.9153e+00, -2.6650e+00, -2.0497e+02,  3.1970e+01,  2.2819e+01, -3.5932e+01, -2.2110e+00, -1.5556e+00, -5.5376e+01, -4.8798e+00, -3.2621e+00, -1.6737e+02, -1.5371e+01, -9.7567e+00, -1.9757e+02,  3.0767e+01,  2.1953e+01,
         -5.5633e+01,  7.8743e+00,  5.4546e+00, -4.3314e+01,  5.7778e+00,  3.9478e+00]], grad_fn=<UnsqueezeBackward0>)


In [50]:
output_model3 = model.model3(input_model3)

In [54]:
print(output_model3.shape)
print(output_model3)
_, predicted = torch.max(output_model3, 1)
print(predicted.shape)
print(predicted)

torch.Size([1, 3])
tensor([[1.0050e-17, 7.6293e-10, 1.0000e+00]], grad_fn=<SoftmaxBackward0>)
torch.Size([1])
tensor([2])


In [44]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class H97_ANN(nn.Module):
    def __init__(self):
        # Use this for data version 3
        super(H97_ANN, self).__init__()
        self.fc1 = nn.Linear(12*3 + 5*3 + 1*3, 97)
        self.fc2 = nn.Linear(97, 3)
        self.dropout = nn.Dropout(0.3)
        # Khởi tạo trọng số tùy chỉnh cho fc1
        self._init_weights()

    def _init_weights(self):
        with torch.no_grad():
            # Trọng số liên quan đến các chiều 1 đến 36 và 54
            self.fc1.weight[:, :36].uniform_(-0.3, 0.3)  # Giá trị nhỏ hơn
            self.fc1.weight[:, 51:].uniform_(-0.15, 0.15)   # Giá trị nhỏ hơn

            # Trọng số liên quan đến các chiều 37 đến 50
            self.fc1.weight[:, 36:50].uniform_(-1, 1)  # Giá trị lớn hơn

    def forward(self, x):
        # Kiểm tra kích thước của tensor đầu vào
        print("Kích thước của tensor đầu vào:", x.size())

        # x size is [batch_size, 12*3 + 5*3 + 1*3]
        x = self.fc1(x)
        x = self.dropout(x)
        x = F.relu(x)
        x = self.fc2(x)

        # Kiểm tra kích thước của tensor trước khi áp dụng softmax
        print("Kích thước của tensor trước softmax:", x.size())

        # Đảm bảo rằng chiều dim hợp lệ cho softmax
        if x.dim() == 2 and x.size(1) == 3:
            x = F.softmax(x, dim=1)  # Softmax applied along the class dimension
        else:
            raise ValueError(f"Kích thước của tensor không hợp lệ cho softmax: {x.size()}")
        
        return x

# Tạo một mô hình và dữ liệu đầu vào giả định
model = H97_ANN()
input_model3 = torch.randn(5, 12*3 + 5*3 + 1*3)  # Giả định đầu vào có kích thước [batch_size, 12*3 + 5*3 + 1*3]

# Gọi mô hình
output_model3 = model(input_model3)
print(output_model3)


Kích thước của tensor đầu vào: torch.Size([5, 54])
Kích thước của tensor trước softmax: torch.Size([5, 3])
tensor([[0.2390, 0.2457, 0.5152],
        [0.6028, 0.1233, 0.2740],
        [0.8679, 0.1228, 0.0093],
        [0.3685, 0.5975, 0.0340],
        [0.2838, 0.2229, 0.4933]], grad_fn=<SoftmaxBackward0>)
